### ISSUE TITLE
Currency object is not JSON serializable

### ISSUE THREAD

**Issue by baneizalfe** [panosl/django-currencies#30] opened 2015-11-14 00:01 UTC
I keep getting <Currency: Currency object> is not JSON serializable

**Comment by einarf** [comment] 2016-02-11 07:04
The problem is that the context manager assigns the current currency model directly as a session variable. In more recent versions of Django, JSONSerializer is default for session data serialization. Django doesn't know how to serialize the currency object.

It would have been simpler if the session only stored the models pk.

**Comment by einarf** [comment] 2016-02-11 10:11
I discovered the develop branch in this project. You should use that instead.

**Comment by panosl** [comment] 2016-05-17 10:23
develop branch has been merged, marking this as closed!

**Closed by panosl** 2016-05-17 10:23 UTC
